### PR TITLE
Feature jj

### PR DESCRIPTION
**Pull request by jjdii**
These changes are worth it. Trust me.

**We documented the following git verbs:**
- bisect
- grep
- log
- show
- status
- branch

### CODE REVIEW

**Comment by jjdii** [comment]
We made the changes you requested, boss. Should we delete the readme?

**Comment by tripott** [comment]
Remove any duplicate documentation in the readme.

**Comment by tripott** [comment]
Hey @m-o-n-t-y.  Nice work.

**Comment by tripott** [comment]
@curreythomas .  You are a good person.

**Comment by tripott** [comment]
@jjdii Im loving the smooth jazz sounds.

**Pull request merged**
